// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdOgW4T2mV_GlEKQpukSHIHGZzPyVu37A',
    appId: '1:890946382807:web:ace4c6d3f909db80e77992',
    messagingSenderId: '890946382807',
    projectId: 'college-seminar',
    authDomain: 'college-seminar.firebaseapp.com',
    storageBucket: 'college-seminar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0uM5FMi2MUa2DBnZhOj7DAKXQnAVDmqo',
    appId: '1:890946382807:android:66ae74e204af36cfe77992',
    messagingSenderId: '890946382807',
    projectId: 'college-seminar',
    storageBucket: 'college-seminar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmo4D2hBFo-Ffbw9FKWZoN_n_Wx7gXBO4',
    appId: '1:890946382807:ios:d5149848881a6371e77992',
    messagingSenderId: '890946382807',
    projectId: 'college-seminar',
    storageBucket: 'college-seminar.firebasestorage.app',
    iosBundleId: 'com.example.seminar2',
  );
}
